### PR TITLE
feat: add readme for Git session

### PR DESCRIPTION
**Pull request by sanjayankur31**
How does this look @OCNS/software-wg ?

Anything else that it should cover (or is this too much for one session?)

### CODE REVIEW

**Review by joewgraham — APPROVED** [review]
Looks great to me!

**Comment by kernfel** [comment]
I'd suggest ``fixed-width markup`` for the various commands in the prerequisites and topics section. Other than that, this looks good!

**Comment by appukuttan-shailesh** [comment]
Looks good :ok_hand:

**Comment by sanjayankur31** [comment]
Thanks @kernfel , fixed the markup now, and added `gitignore` (with a typo to demonstrate `git bisect`). Merging.

**Pull request merged**
