### PR TITLE
Update bash readme

### PR DESCRIPTION
**Pull request by kernfel**
The list of topics has grown to include things I'll have to read up on just a little. Further comments are always welcome!

### CODE REVIEW

**Comment by sanjayankur31** [comment]
LGTM :+1:

I've just checked to find that some of my suggestions are part of coreutils, and not bash built-ins, so we'll have to check if they're available on Git for windows or not. I'll see if I can find a windows machine to verify this.

**Comment by kernfel** [comment]
Checked. Everything seems to be included, apart from `man` and `apropos`. Emacs mode keybindings and mouse pasting works, though, which is mildly unexpected and rather nice.

**Comment by kernfel** [comment]
Incidentally, the Git for Windows installation asks a ton of rather involved questions and selects `vim` as the default editor. I wonder if we should add some guidance...

**Comment by sanjayankur31** [comment]
> Checked. Everything seems to be included, apart from `man` and `apropos`. 

Eh, that's unfortunate. This must be to reduce the size of the installer since docs take quite a bit of space.



> Incidentally, the Git for Windows installation asks a ton of rather involved questions and selects `vim` as the default editor. I wonder if we should add some guidance...

Uh, yeh, I don't see any docs on their website. I wonder if there are guides out there already and we could recommend one?

**Comment by mstimberg** [comment]
Argh, I forgot about all these questions... The SWC instructions try to go through this step for step, see: 
https://carpentries.github.io/workshop-template/
under "The Bash Shell" and click on the Windows tab. I think you should ignore the video, it still mentions the "SWC installer" which as far as I know is not necessary anymore.

**Pull request merged**
